name: VSIX Build

on:
  workflow_dispatch:
    inputs:
      comments:
        description: "Build VSIX"
        required: false
        default: "Nothing"
        type: string

jobs:
  build_information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$BUILD_CMTS"
        env: 
          BUILD_CMTS: ${{ inputs.comments }}

  build_vsix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Acquire Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Adjust the version as needed

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Build VSIX
        run: vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v3
        with:
          name: poprock.vsix
          path: .
